title: Thomas Franklin
description: ğŸ¤·â€â™‚ï¸ not sure what I am doing.
collections:
  category:
    output: true

paginate: 5
paginate_path: "/blog/page/:num"

sass:
  style: compressed
  sass_dir: ./assets/css/

defaults:
  -
    scope:
      path: ""
      type: "category"
    values:
      layout: category
