title: Thomas Franklin
description: ğŸ¤·â€â™‚ï¸ not sure what I am doing.
collections:
  category:
    output: true

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

paginate: 5
paginate_path: "/blog/page/:num"

sass:
  style: compressed
  sass_dir: ./assets/css/

defaults:
  -
    scope:
      path: ""
      type: "category"
    values:
      layout: category
